version: '3.2'
services:
  db-test:
    image: postgres
    restart: always
    ports:
      - '54321:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
  app:
    build:
      context: .
      args:
        database_url: postgresql://user:pwd@db-test:5432/db
    entrypoint: /e2e/scripts/wait_for_it.sh db-test:5432 -- npm run start:full
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://user:pwd@db-test:5432/db
      - CLIENT_SECRET=some_strang3_s3cr3t
    ports:
      - 8080:8080
    volumes:
      # share everything BUT node_modules from the host
      - .:/backend
      - /backend/node_modules
      - .:/frontend
      - /frontend/node_modules
      - ./tests-e2e:/e2e
    depends_on:
      - db-test
  cypress:
    image: 'cypress/included:3.2.0'
    entrypoint: /e2e/scripts/wait_for_it.sh app:8080 -- cypress run --record --key 5619557e-5109-4f0c-8043-d9565867395b
    environment:
      - CYPRESS_baseUrl=http://app:8080
    working_dir: /e2e
    volumes:
      - ./tests-e2e:/e2e
